### ISSUE TITLE
Support ESLint 9.x

### ISSUE THREAD

**Issue by ericberens** [infctr/eslint-plugin-typescript-sort-keys#77]
Similar to https://github.com/infctr/eslint-plugin-typescript-sort-keys/issues/42

It would be great to officially support ESLint v9.x now that it has been [released](https://eslint.org/blog/2024/04/eslint-v9.0.0-released/).

**Comment by shellscape** [comment]
Additionally, the peerDep on `@typescript-eslint/parser` is two major versions behind.

**Comment by BenJackGill** [comment]
+1 would also love this

**Comment by moontai0724** [comment]
For those who want to use this plugin before it officially support v9, set this up:

```typescript
// @ts-check
import pluginJs from "@eslint/js";
import { config as typedConfig, configs as tsConfigs } from "typescript-eslint";
import typescriptSortKeys from "eslint-plugin-typescript-sort-keys";

export default typedConfig(
  { ignores: ["node_modules"] },
  pluginJs.configs.recommended,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        ecmaVersion: "latest",
        sourceType: "module",
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    files: ["**/*.ts"],
    extends: [...tsConfigs.strictTypeChecked],
  },
  {
    plugins: {
      "typescript-sort-keys": typescriptSortKeys,
    },
    rules: {
      "typescript-sort-keys/interface": "error",
      "typescript-sort-keys/string-enum": "error",
    },
  }
);
```

The installation progress will warn you that the version is incompatible but it's fine.

**Comment by skilbjo** [comment]
@moontai0724 any workaround for the below? (i have the config you provided)

```
@Johns-MacBook-Air:config-rc $ npm run lint
> eslint .


Oops! Something went wrong! :(

ESLint: 9.12.0

ConfigError: Config (unnamed): Key "plugins": Cannot redefine plugin "typescript-sort-keys".
    at rethrowConfigError (/Users/skilbjo/dev/config-rc/node_modules/@eslint/config-array/dist/cjs/index.cjs:303:8)
    at /Users/skilbjo/dev/config-rc/node_modules/@eslint/config-array/dist/cjs/index.cjs:1098:5
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfigWithStatus (/Users/skilbjo/dev/config-rc/node_modules/@eslint/config-array/dist/cjs/index.cjs:1091:43)
    at FlatConfigArray.getConfig (/Users/skilbjo/dev/config-rc/node_modules/@eslint/config-array/dist/cjs/index.cjs:1120:15)
    at entryFilter (/Users/skilbjo/dev/config-rc/node_modules/eslint/lib/eslint/eslint-helpers.js:286:40)
    at async NodeHfs.<anonymous> (file:///Users/skilbjo/dev/config-rc/node_modules/@humanfs/core/src/hfs.js:560:24)
    at async NodeHfs.walk (file:///Users/skilbjo/dev/config-rc/node_modules/@humanfs/core/src/hfs.js:600:3)
    at async globSearch (/Users/skilbjo/dev/config-rc/node_modules/eslint/lib/eslint/eslint-helpers.js:327:26)
    at async Promise.allSettled (index 0)
```

**Comment by moontai0724** [comment]
@skilbjo I've updated to my current version and also uploaded a workaround here: https://github.com/moontai0724/workaround-eslint-v9-sort-keys/blob/main/eslint.config.js

**Comment by FlorianWendelborn** [comment]
FYI there’s also <https://perfectionist.dev/> which seems pretty feature-complete and can handle most other types of sorting too

**Comment by moontai0724** [comment]
@FlorianWendelborn oh my, that seems FANTASTIC!

**Comment by Smrtnyk** [comment]
@infctr would you accept a PR for this?

**Comment by RampantDespair** [comment]
Any news?
